export const GENRE_IDS = {
  action: 28,
  adventure: 12,
  animation: 16,
  comedy: 35,
  crime: 80,
  documentary: 99,
  drama: 18,
  family: 10751,
  fantasy: 14,
  history: 36,
  horror: 27,
  music: 10402,
  mystery: 9648,
  romance: 10749,
  scienceFiction: 878,
  thriller: 53,
  war: 10752,
  western: 37,
} as const;

/** Curated genre chips shown on Home / Browse, ordered for browsing flow. */
export const BROWSE_GENRES: { id: number; name: string }[] = [
  { id: GENRE_IDS.action, name: 'Action' },
  { id: GENRE_IDS.adventure, name: 'Adventure' },
  { id: GENRE_IDS.drama, name: 'Drama' },
  { id: GENRE_IDS.comedy, name: 'Comedy' },
  { id: GENRE_IDS.thriller, name: 'Thriller' },
  { id: GENRE_IDS.horror, name: 'Horror' },
  { id: GENRE_IDS.romance, name: 'Romance' },
  { id: GENRE_IDS.animation, name: 'Animation' },
  { id: GENRE_IDS.family, name: 'Family' },
  { id: GENRE_IDS.documentary, name: 'Documentary' },
  { id: GENRE_IDS.fantasy, name: 'Fantasy' },
  { id: GENRE_IDS.mystery, name: 'Mystery' },
  { id: GENRE_IDS.crime, name: 'Crime' },
  { id: GENRE_IDS.scienceFiction, name: 'Science Fiction' },
  { id: GENRE_IDS.war, name: 'War' },
  { id: GENRE_IDS.western, name: 'Western' },
];
